#!/bin/sh
# Swift Ring Building
# Ring Build execute on object server 1 [ob1]
#rm -rf /etc/swift/*.ring.gz
cd /etc/swift
swift-ring-builder account.builder create 17 3 1
swift-ring-builder container.builder create 17 3 1
swift-ring-builder object.builder create 17 3 1
#*****************************************#
# Execute ring generate sh ring_generate  #
sh ring_generate                          #
#*****************************************#
swift-ring-builder account.builder
swift-ring-builder container.builder
swift-ring-builder object.builder
# ring rebalance
swift-ring-builder account.builder rebalance
swift-ring-builder container.builder rebalance
swift-ring-builder object.builder rebalance
#*********************************************#
# Execute ring distribute sh ring_distribute  #
sh ring_distribute                              #
#*********************************************#
